packages:

  # concretization preferences
  all:
    compiler: [gcc@8.1.1]
    providers:
      mpi: [spectrum-mpi]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      scalapack: [netlib-scalapack]

  # system modules externals. Uses explicit paths rather than the modules
  # feature of spack, more robust and simpler in some cases.
  spectrum-mpi:
    modules:
      spectrum-mpi@10.3.1.2-20200121%gcc@8.1.1: spectrum-mpi/10.3.1.2-20200121
      spectrum-mpi@10.3.1.2-20200121%gcc@9.1.0: spectrum-mpi/10.3.1.2-20200121
      spectrum-mpi@10.3.1.2-20200121%pgi@19.9: spectrum-mpi/10.3.1.2-20200121
    buildable: False

  cuda:
    paths:
      cuda@10.1.243: /sw/summit/cuda/10.1.243
      cuda@11.0.3: /sw/summit/cuda/11.0.3
    buildable: False

  # build a libfabric that actually supports RDMA
  libfabric:
    variants: fabrics=sockets,tcp,udp,verbs,rxm

  rdma-core:
    paths:
      rdma-core: /usr
    buildable: False

  kokkos:
    variants: +cuda cuda_arch=70 +openmp +volta70 +cuda_lambda +wrapper

  dataspaces:
    version: [develop]
    variants: +fpic maxdims=10 network-type=infiniband +dimes

  fftw:
    paths:
      fftw@3.3.8%gcc@8.1.1: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/fftw-3.3.8-in2y7enjd3memwrmamnoxvsmx37mse7t
      fftw@3.3.8%pgi@19.9: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-19.9/fftw-3.3.8-wri566ow7qlimailhyznou5cfm4h362z

  netlib-lapack:
    paths:
      netlib-lapack@3.8.0%gcc@8.1.1: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/netlib-lapack-3.8.0-p74bsneivus4jck562lq7drw2s7i4ytd
      netlib-lapack@3.8.0%pgi@19.9:  /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-19.9/netlib-lapack-3.8.0-osgnhlqnprebssng2vsxn3dtgmwfutbb

  netlib-scalapack:
    paths:
      netlib-scalapack@2.0.2%gcc@8.1.1: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/netlib-scalapack-2.0.2-7x3lv7z2lzfbe5kfwlt2aajkx4hvmgdm
      netlib-lapack@3.8.0%pgi@19.9:  /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-19.9/netlib-lapack-3.8.0-osgnhlqnprebssng2vsxn3dtgmwfutbb

  hdf5:
    paths:
      hdf5@1.10.4%gcc@8.1.1: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/hdf5-1.10.4-xukzkcwzv4qfpd4l2ddw4zo7c45dyigy
      hdf5@1.10.4%gcc@9.1.0: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-9.1.0/hdf5-1.10.4-x2ynbtekhviirvbzrulqvy6dlympzvrq
      hdf5@1.10.4%pgi@19.9: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-19.9/hdf5-1.10.4-w5ddmrlsb4zyhwrfl2jfty3pykqszq53
    variants: +fortran +hl +mpi

  python:
    paths:
      python@3.7.0: /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/python-3.7.0-ei3mpdncii74xsn55t5kxpuc46i3oezn/
      python@2.7.15: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/python-2.7.15-rzeo24etdlaremohlyeb55b37gttl2iy

  effis:
    version: [develop]

#  cmake:
#    paths:
#      cmake@3.15.2: /sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/cmake-3.15.2-xit2o3iepxvqbyku77lwcugufilztu7t
#    buildable: False

  # manual externals
  rdma-core:
    paths:
      rdma-core@20: /usr

  # Auto generated with bin/spack-gen-external-packages.py
  autoconf:
    paths:
      autoconf@2.69: /usr

  automake:
    paths:
      automake@1.13.4: /usr

  bison:
    paths:
      bison@3.0.4: /usr

  libtool:
    paths:
      libtool@2.4.2: /usr

  m4:
    paths:
      m4@1.4.16: /usr

  flex:
    paths:
      flex@2.5.37: /usr

  pkg-config:
    paths:
      pkg-config@0.27.1: /usr

  binutils:
    variants: +libiberty +headers
    paths:
      binutils@2.27: /usr

  curl:
    paths:
      curl@7.29.0: /usr

  gawk:
    paths:
      gawk@4.0.2: /usr

  diffutils:
    paths:
      diffutils@3.3: /usr

  zsh:
    paths:
      zsh@5.0.2: /usr

  zlib:
    paths:
      zlib@1.2.7: /usr

  xz:
    paths:
      xz@5.2.2: /usr

  tar:
    paths:
      tar@1.26: /usr

  lz4:
    paths:
      lz4@1.7.5: /usr

  snappy:
    paths:
      snappy@1.1.0: /usr

  openssl:
    paths:
      openssl@1.0.2k: /usr

  gettext:
    paths:
      gettext@0.19.8.1: /usr

  ncurses:
    paths:
      ncurses@5.9: /usr

  readline:
    paths:
      readline@6.2: /usr

  gmp:
    paths:
      gmp@6.0.0: /usr

  libffi:
    paths:
      libffi@3.0.13: /usr
